project_id = "ggvhwxpaovfvoyvzixqw"

[functions.save-search-results]
verify_jwt = false

[functions.release-api-slot]
verify_jwt = false

[functions.update-job-status]
verify_jwt = false

[functions.validate-reset-token]
verify_jwt = false

[functions.crm-test-connection]
verify_jwt = false
