// This file is automatically generated. Do not edit it directly.
import { createClient, FunctionInvokeOptions } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * Wrapper around supabase.functions.invoke that refreshes the session first
 * and extracts the real error message from non-2xx responses.
 */
export async function invokeEdgeFunction<T = unknown>(
  functionName: string,
  options?: FunctionInvokeOptions,
): Promise<{ data: T | null; error: Error | null }> {
  const { error: refreshError } = await supabase.auth.refreshSession();
  if (refreshError) {
    return {
      data: null,
      error: new Error("Session expired. Please log in again."),
    };
  }

  const { data, error } = await supabase.functions.invoke(functionName, options);

  if (error) {
    // FunctionsHttpError stores the raw Response in error.context — parse it for the real message
    const ctx = (error as any).context;
    if (ctx && typeof ctx.json === "function") {
      try {
        const body = await ctx.json();
        const realMessage = body?.error || body?.message;
        if (realMessage) {
          return { data: body as T, error: new Error(realMessage) };
        }
      } catch {
        // response already consumed or not JSON — fall through
      }
    }
    return { data, error };
  }

  return { data: data as T, error: null };
}