// This file is automatically generated. Do not edit it directly.
import { createClient, FunctionInvokeOptions } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * Wrapper around supabase.functions.invoke that refreshes the session first
 * and extracts the real error message from non-2xx responses.
 */
export async function invokeEdgeFunction<T = unknown>(
  functionName: string,
  options?: FunctionInvokeOptions,
): Promise<{ data: T | null; error: Error | null }> {
  // Force session refresh to ensure a valid access token
  const { error: refreshError } = await supabase.auth.refreshSession();
  if (refreshError) {
    return {
      data: null,
      error: new Error("Session expired. Please log in again."),
    };
  }

  const { data, error } = await supabase.functions.invoke(functionName, options);

  if (error) {
    // supabase.functions.invoke returns a generic "Edge Function returned a non-2xx status code"
    // but data may still contain the real error from the function's JSON response
    const realMessage = data?.error || data?.message;
    if (realMessage) {
      return { data, error: new Error(realMessage) };
    }
    return { data, error };
  }

  return { data: data as T, error: null };
}